import { getLightness } from "./helpers"

const originalThemes = [
    {
        name: "JustJot Light",
        colBg: "#e0e0e0",
        colMain: "#0098a9",
        colSub: "#777777",
        colText: "#121212",
        colDanger: "#fa5252",
    },
    {
        name: "JustJot Dark",
        colBg: "#121212",
        colMain: "#0098a9",
        colSub: "#777777",
        colText: "#e0e0e0",
        colDanger: "#fa5252",
    },
    {
        name: "Pura Tela",
        colBg: "#E3E0D6",
        colMain: "#1AC4F5",
        colSub: "#323740",
        colText: "#232042",
        colDanger: "#bb474f",
    },
] as const

/**
 * Theme data adapted from Monkey Type
 * Source: https://github.com/monkeytypegame/monkeytype
 * License: GNU General Public License v3 (GPLv3)
 * Credits to Monkey Type contributors
 */
const monkeyTypeThemes = [
    {
        name: "8008",
        colBg: "#333a45",
        colMain: "#f44c7f",
        colSub: "#939eae",
        colText: "#e9ecf0",
        colDanger: "#da3333",
    },
    {
        name: "9009",
        colBg: "#eeebe2",
        colMain: "#080909",
        colSub: "#99947f",
        colText: "#080909",
        colDanger: "#c87e74",
    },
    {
        name: "Alduin",
        colBg: "#1c1c1c",
        colMain: "#dfd7af",
        colSub: "#444444",
        colText: "#f5f3ed",
        colDanger: "#af5f5f",
    },
    {
        name: "Bento",
        colBg: "#2d394d",
        colMain: "#ff7a90",
        colSub: "#4a768d",
        colText: "#fffaf8",
        colDanger: "#ee2a3a",
    },
    {
        name: "Bliss",
        colBg: "#262727",
        colMain: "#f0d3c9",
        colSub: "#665957",
        colText: "#ffffff",
        colDanger: "#bd4141",
    },
    {
        name: "Blue Dolphin",
        colBg: "#003950",
        colMain: "#ffcefb",
        colSub: "#00e4ff",
        colText: "#82eaff",
        colDanger: "#ffbde6",
    },
    {
        name: "Breeze",
        colBg: "#e8d5c4",
        colMain: "#7d67a9",
        colSub: "#3a98b9",
        colText: "#1b4c5e",
        colDanger: "#7d67a9",
    },
    {
        name: "Bushido",
        colBg: "#242933",
        colMain: "#ec4c56",
        colSub: "#596172",
        colText: "#f6f0e9",
        colDanger: "#ec4c56",
    },
    {
        name: "Carbon",
        colBg: "#313131",
        colMain: "#f66e0d",
        colSub: "#616161",
        colText: "#f5e6c8",
        colDanger: "#e72d2d",
    },
    {
        name: "Cheesecake",
        colBg: "#fdf0d5",
        colMain: "#8e2949",
        colSub: "#d91c81",
        colText: "#3a3335",
        colDanger: "#5cf074",
    },
    {
        name: "Comfy",
        colBg: "#4a5b6e",
        colMain: "#f8cdc6",
        colSub: "#9ec1cc",
        colText: "#f5efee",
        colDanger: "#c9465e",
    },
    {
        name: "Copper",
        colBg: "#442f29",
        colMain: "#b46a55",
        colSub: "#7ebab5",
        colText: "#e7e0de",
        colDanger: "#a32424",
    },
    {
        name: "Deku",
        colBg: "#058b8c",
        colMain: "#b63530",
        colSub: "#255458",
        colText: "#f7f2ea",
        colDanger: "#b63530",
    },
    {
        name: "Diner",
        colBg: "#537997",
        colMain: "#c3af5b",
        colSub: "#445c7f",
        colText: "#dfdbc8",
        colDanger: "#ad5145",
    },
    {
        name: "Dracula",
        colBg: "#282a36",
        colMain: "#bd93f9",
        colSub: "#6272a4",
        colText: "#f8f8f2",
        colDanger: "#ff5555",
    },
    {
        name: "Fleuriste",
        colBg: "#c6b294",
        colMain: "#405a52",
        colSub: "#64374d",
        colText: "#091914",
        colDanger: "#990000",
    },
    {
        name: "Godspeed",
        colBg: "#eae4cf",
        colMain: "#9abbcd",
        colSub: "#ada998",
        colText: "#646669",
        colDanger: "#ca4754",
    },
    {
        name: "Hammerhead",
        colBg: "#030613",
        colMain: "#4fcdb9",
        colSub: "#213c53",
        colText: "#e2f1f5",
        colDaner: "#e32b2b",
    },
    {
        name: "Horizon",
        colBg: "#1c1e26",
        colMain: "#c4a88a",
        colSub: "#db886f",
        colText: "#bbbbbb",
        colDanger: "#d55170",
    },
    {
        name: "Laser",
        colBg: "#221b44",
        colMain: "#009eaf",
        colSub: "#b82356",
        colText: "#dbe7e8",
        colDanger: "#a8d400",
    },
    {
        name: "Luna",
        colBg: "#221c35",
        colMain: "#f67599",
        colSub: "#5a3a7e",
        colText: "#ffe3eb",
        colDanger: "#efc050",
    },
    {
        name: "Matrix",
        colBg: "#000000",
        colMain: "#15ff00",
        colSub: "#006500",
        colText: "#d1ffcd",
        colDanger: "#da3333",
    },
    {
        name: "Miami",
        colBg: "#f35588",
        colMain: "#05dfd7",
        colSub: "#94294c",
        colText: "#f0e9ec",
        colDanger: "#fff591",
    },
    {
        name: "Miami Nights",
        colBg: "#18181a",
        colMain: "#e4609b",
        colSub: "#47bac0",
        colText: "#ffffff",
        colDanger: "#fff591",
    },
    {
        name: "Modern Dolch",
        colBg: "#2d2e30",
        colMain: "#7eddd3",
        colSub: "#54585c",
        colText: "#e3e6eb",
        colDanger: "#d36a7b",
    },
    {
        name: "Modern Dolch Light",
        colBg: "#dbdbdb",
        colMain: "#8fd1c3",
        colSub: "#a3a2a2",
        colText: "#454545",
        colDanger: "#ea8a9a",
    },
    {
        name: "Monokai",
        colBg: "#272822",
        colMain: "#a6e22e",
        colSub: "#e6db74",
        colText: "#e2e2dc",
        colDanger: "#f92672",
    },
    {
        name: "Nautilus",
        colBg: "#132237",
        colMain: "#ebb723",
        colSub: "#0b4c6c",
        colText: "#1cbaac",
        colDanger: "#da3333",
    },
    {
        name: "Nord",
        colBg: "#242933",
        colMain: "#88c0d0",
        colSub: "#929aaa",
        colText: "#d8dee9",
        colDanger: "#bf616a",
    },
    {
        name: "Norse",
        colBg: "#242425",
        colMain: "#2b5f6d",
        colSub: "#505b5e",
        colText: "#ccc2b1",
        colDanger: "#7e2a2a",
    },
    {
        name: "Oblivion",
        colBg: "#313231",
        colMain: "#a5a096",
        colSub: "#5d6263",
        colText: "#f7f5f1",
        colDanger: "#dd452e",
    },
    {
        name: "Pale Nimbus",
        colBg: "#433e4c",
        colMain: "#94ffc2",
        colSub: "#ffaca3",
        colText: "#feffdb",
        colDanger: "#ff5c5c",
    },
    {
        name: "Pulse",
        colBg: "#181818",
        colMain: "#17b8bd",
        colSub: "#53565a",
        colText: "#e5f4f4",
        colDanger: "#da3333",
    },
    {
        name: "Retro",
        colBg: "#dad3c1",
        colMain: "#1d1b17",
        colSub: "#918b7d",
        colText: "#1d1b17",
        colDanger: "#bf616a",
    },
    {
        name: "Ryujinscales",
        colBg: "#081426",
        colMain: "#f17754",
        colSub: "#ffbc90",
        colText: "#ffe4bc",
        colDanger: "#ca4754",
    },
    {
        name: "Serika",
        colBg: "#e1e1e3",
        colMain: "#e2b714",
        colSub: "#aaaeb3",
        colText: "#323437",
        colDanger: "#da3333",
    },
    {
        name: "Serika Dark",
        colBg: "#323437",
        colMain: "#e2b714",
        colSub: "#646669",
        colText: "#d1d0c5",
        colDanger: "#ca4754",
    },
    {
        name: "Slambook",
        colBg: "#fffdde",
        colMain: "#03001c",
        colSub: "#1c82adc4",
        colText: "#13005a",
        colDanger: "#f900bf",
    },
    {
        name: "Solarized Dark",
        colBg: "#002b36",
        colMain: "#859900",
        colSub: "#2aa198",
        colText: "#268bd2",
        colDanger: "#d33682",
    },
    {
        name: "Solarized Light",
        colBg: "#fdf6e3",
        colMain: "#859900",
        colSub: "#2aa198",
        colText: "#181819",
        colDanger: "#d33682",
    },
    {
        name: "Solarized Osaka",
        colBg: "#00141a",
        colMain: "#859900",
        colSub: "#2aa198",
        colText: "#eee8d5",
        colDanger: "#dc322f",
    },
    {
        name: "Sonokai",
        colBg: "#2c2e34",
        colMain: "#9ed072",
        colSub: "#e7c664",
        colText: "#e2e2e3",
        colDanger: "#fc5d7c",
    },
    {
        name: "Suisei",
        colBg: "#0b0e13",
        colMain: "#6ee7b7",
        colSub: "#5eead4",
        colText: "#ecfeff",
        colDanger: "#f87171",
    },
    {
        name: "Sweden",
        colBg: "#0058a3",
        colMain: "#ffcc02",
        colSub: "#57abdb",
        colText: "#ffffff",
        colDanger: "#e74040",
    },
    {
        name: "Trackday",
        colBg: "#1a1a1a",
        colMain: "#ff4d4d",
        colSub: "#4a4a4a",
        colText: "#ffffff",
        colDanger: "#ff3333",
    },
    {
        name: "Vesper",
        colBg: "#1d1d2b",
        colMain: "#c4b5fc",
        colSub: "#6e6a9e",
        colText: "#e0e0e6",
        colDanger: "#c4b5fc",
    },
    {
        name: "Vesper Light",
        colBg: "#f4f4f8",
        colMain: "#6e6a9e",
        colSub: "#a5a5bd",
        colText: "#1d1d2b",
        colDanger: "#6e6a9e",
    },
    {
        name: "VSCode",
        colBg: "#1e1e1e",
        colMain: "#007acc",
        colSub: "#3e3e42",
        colText: "#d4d4d4",
        colDanger: "#f14c4c",
    },
    {
        name: "Witch Girl",
        colBg: "#2d1f2d",
        colMain: "#ffc8dd",
        colSub: "#dfb4e4",
        colText: "#f5e6f0",
        colDanger: "#ff9ebd",
    },
    {
        name: "Aurora",
        colBg: "#011926",
        colMain: "#00e980",
        colSub: "#245c69",
        colText: "#fff",
        colDanger: "#b94da1",
    },
    {
        name: "Botanical",
        colBg: "#7b9c98",
        colMain: "#eaf1f3",
        colSub: "#495755",
        colText: "#eaf1f3",
        colDanger: "#f6c9b4",
    },
    {
        name: "Cafe",
        colBg: "#ceb18d",
        colMain: "#14120f",
        colSub: "#d4d2d1",
        colText: "#14120f",
        colDanger: "#c82931",
    },
    {
        name: "Honey",
        colBg: "#f2aa00",
        colMain: "#fff546",
        colSub: "#a66b00",
        colText: "#f3eecb",
        colDanger: "#df3333",
    },
    {
        name: "Menthol",
        colBg: "#00c18c",
        colMain: "#ffffff",
        colSub: "#186544",
        colText: "#ffffff",
        colDanger: "#e03c3c",
    },
    {
        name: "Retrocast",
        colBg: "#07737a",
        colMain: "#88dbdf",
        colSub: "#f3e03b",
        colText: "#ffffff",
        colDanger: "#ff585d",
    },
] as const

type Theme = (typeof originalThemes)[number]

const allThemes: Theme[] = [
    ...originalThemes,
    ...(monkeyTypeThemes as unknown as Theme[]),
].sort((a, b) => getLightness(b.colBg) - getLightness(a.colBg))

export const themes = allThemes as readonly Theme[]

export type ThemeName = Theme["name"]
